//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicePK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBusinessDirectory
    {
        public long Id { get; set; }
        public string BusinessName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Landline { get; set; }
        public string Mobile { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> IsTrader { get; set; }
        public Nullable<bool> IsMiller { get; set; }
        public Nullable<bool> IsExporter { get; set; }
        public Nullable<bool> IsImporter { get; set; }
        public string MillingCapacity { get; set; }
        public Nullable<bool> ThirdPartyProcessing { get; set; }
    }
}
