//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicePK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyRate
    {
        public long DailyRateId { get; set; }
        public System.DateTime DailyRateDate { get; set; }
        public long ProductId { get; set; }
        public long CityId { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
    }
}
