//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicePK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFacilitator
    {
        public long FacilitatorId { get; set; }
        public string FacilitatorName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public string Type { get; set; }
    }
}
