//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RicePK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public long ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<long> ProductCategoryId { get; set; }
    
        public virtual tblProductCategory tblProductCategory { get; set; }
    }
}
